### PR TITLE
updated next and next-seo to latest version

### PR DESCRIPTION
**Pull request by hugelive**
updated next from 9.3.6 to 9.4.1
updated next-seo from 4.4.0 to 4.5.0

### CODE REVIEW

**Comment by hugeliveux** [comment]
Something is wrong. Please refer to issue #58

**Comment by hugelive** [comment]
@hugeliveux add mongo connection string and try again please

**Comment by hugelive** [comment]
> It works out fine!

worked out just "fine"? C'mon man srsly?

**Comment by hugeliveux** [comment]
> > It works out fine!
> 
> worked out just "fine"? C'mon man srsly?

It's Magic!

**Comment by hugelive** [comment]
> > > It works out fine!
> > 
> > 
> > worked out just "fine"? C'mon man srsly?
> 
> It's Magic!

now we're talking

**Pull request merged**
